// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS_LjZMXs2zeMDm3e0tJTKgLNHs06yXhA',
    appId: '1:898177747814:web:89b41232cbe4b6c6c056a7',
    messagingSenderId: '898177747814',
    projectId: 'unilift-72e26',
    authDomain: 'unilift-72e26.firebaseapp.com',
    storageBucket: 'unilift-72e26.appspot.com',
    measurementId: 'G-HM8TB8FXFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtkaJDxCMIghNIK-OsMCS9nd_FX8izJ3g',
    appId: '1:898177747814:android:03df2775a2258c6cc056a7',
    messagingSenderId: '898177747814',
    projectId: 'unilift-72e26',
    storageBucket: 'unilift-72e26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbBnwHGLsdYcLrYZTiUtQrX2DLt9GQIwg',
    appId: '1:898177747814:ios:dfd0250d9c922c05c056a7',
    messagingSenderId: '898177747814',
    projectId: 'unilift-72e26',
    storageBucket: 'unilift-72e26.appspot.com',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbBnwHGLsdYcLrYZTiUtQrX2DLt9GQIwg',
    appId: '1:898177747814:ios:dfd0250d9c922c05c056a7',
    messagingSenderId: '898177747814',
    projectId: 'unilift-72e26',
    storageBucket: 'unilift-72e26.appspot.com',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS_LjZMXs2zeMDm3e0tJTKgLNHs06yXhA',
    appId: '1:898177747814:web:78063b48a73fefb1c056a7',
    messagingSenderId: '898177747814',
    projectId: 'unilift-72e26',
    authDomain: 'unilift-72e26.firebaseapp.com',
    storageBucket: 'unilift-72e26.appspot.com',
    measurementId: 'G-E7DJ2ZS67R',
  );

}